# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LetSeeExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LetSeeExample
  pod 'LetSee', :git => 'https://github.com/farshadjahanmanesh/Letsee.git'
  target 'LetSeeExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LetSeeExampleUITests' do
    # Pods for testing
  end

end
